import {
	AntDesignOutlined,
	ApartmentOutlined,
	CloudOutlined,
	CommentOutlined,
	ContainerOutlined,
	CopyrightOutlined,
	DashboardOutlined,
	DatabaseOutlined,
	EyeOutlined,
	FileTextOutlined,
	HistoryOutlined,
	HomeOutlined,
	LineChartOutlined,
	LockOutlined,
	MenuOutlined,
	NodeExpandOutlined,
	RiseOutlined,
	RobotOutlined,
	SafetyOutlined,
	SettingOutlined,
	SisternodeOutlined,
	StockOutlined,
	SubnodeOutlined,
	SyncOutlined,
	TableOutlined,
	TeamOutlined,
	UserOutlined,
} from "@ant-design/icons";
import { EmbeddedIcon, ExternalIcon, OutsidePageIcon, ProfileCardIcon } from "./local-icons";
import { RiAccountCircleLine, RiReactjsLine, RiUserSettingsLine } from "./ri";

/**
 * Icons used in the menu.
 */
export const menuIcons: Record<string, any> = {
	EmbeddedIcon,
	HomeOutlined,
	SafetyOutlined,
	CloudOutlined,
	FileTextOutlined,
	LockOutlined,
	EyeOutlined,
	NodeExpandOutlined,
	SisternodeOutlined,
	SubnodeOutlined,
	OutsidePageIcon,
	AntDesignOutlined,
	ContainerOutlined,
	ExternalIcon,
	RiReactjsLine,
	SettingOutlined,
	UserOutlined,
	TeamOutlined,
	MenuOutlined,
	ApartmentOutlined,
	RiAccountCircleLine,
	ProfileCardIcon,
	RiUserSettingsLine,
	CopyrightOutlined,
	RobotOutlined,
	CommentOutlined,
	HistoryOutlined,
	LineChartOutlined,
	StockOutlined,
	RiseOutlined,
	DatabaseOutlined,
	DashboardOutlined,
	SyncOutlined,
	TableOutlined,
};
